// <auto-generated />
using System;
using Finansys.Data.Repository.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Finansys.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210714165056_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Finansys.Data.Repository.DTOs.CategoriaDTO", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Tb_Categorias");
                });

            modelBuilder.Entity("Finansys.Data.Repository.DTOs.LancamentoDTO", b =>
                {
                    b.Property<string>("LancamentoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CategoriaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("LancamentoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tb_Lancamentos");
                });

            modelBuilder.Entity("Finansys.Data.Repository.DTOs.LancamentoDTO", b =>
                {
                    b.HasOne("Finansys.Data.Repository.DTOs.CategoriaDTO", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
